language: node_js # 声明环境为node
node_js: 
  - 14.16.1

env: # 环境变量,这个环境变量其实下面没用到，忽略
 global:
   - GH_REF: github.com/meixuhong/meixuhong.github.io.git # 我的仓库地址

branches:
  only:
    - hexo # 只对hexo分支构建

cache:
  directories:
    - node_modules # 缓存 node_modules 加快构建速度
    
before_install:               # install 阶段之前执行
  - npm install -g hexo-cli   # 全局安装 Hexo 命令行工具
  - npm install --global gulp-cli

install:                      # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install               # 安装 package.json 中的依赖，将package.json中的库指定版本了，所以后续hexo或者npm有更新时不会因为依赖关系导致出错


script:                       # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean
  - hexo generate             # Hexo 常规命令，执行清理和生成
  - gulp


deploy: # 根据个人情况，这里会有所不同
  provider: pages
  skip_cleanup: true # 构建完成后不清除
  token: $GH_TOKEN # 你刚刚设置的 token
  keep_history: true # 保存历史
  fqdn: meixuhong.com # 自定义域名，使用 username.github.io 可删除
  on:
    branch: hexo # hexo 站点源文件所在的 branch
  local_dir: public 
  target_branch: master # 存放生成站点文件的 branch，使用 username.github.io


# after_success:                # script 阶段成功时执行，构建失败不会执行，其他同上
#   # - git config --local user.name "lm-travis-ci"
#   # - git config --local user.email "lm@meixuhong.com"
#   # - sed -i'' "s~git@github.com:~https://${GH_TOKEN}@${GH_REF}/~" _config.yml  #GH_TOKEN是在Travis-CI上定义的变量，取值来源于Github上的值
#   # - hexo deploy > /dev/null   # 通过 Hexo 的 deploy 命令部署博客
#   - cd ./public
#   - git init
#   - git config --local user.name "lm-travis-ci"
#   - git config --local user.email "lm@meixuhong.com"
#   - git add .
#   - git commit -m "lm@meixuhong.com"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # 通过之前存在Travis-CI里的token以及github仓库的地址推送到相应的master分支

